uint8 MODE_JOINT=0
uint8 MODE_CARTESIAN=1
uint8 MODE_HOME=2
uint8 MODE_ALIGN_Z=3

uint8 ACTION_STOP=0
uint8 ACTION_START=1
uint8 ACTION_KEEPALIVE=2

# Joint targets use degrees. Cartesian targets use
# [X(mm), Y(mm), Z(mm), RX(deg), RY(deg), RZ(deg)].
uint8 mode
float64[6] target
float64 velocity
float64 acceleration
float64 blend_radius
uint8 action

# GUI motion uses Hold-to-run=true, including target, Home and Z alignment.
bool hold_required
---
bool success
string message
